### ISSUE TITLE
[RubyGems] Requesting Ownership Transfer

### ISSUE THREAD

**Issue by andrewmcodes** [bt-rb/bridgetown-minify-html#26]
### Description

RubyGems support asked me to create this issue mentioning that I would like to transfer the Rubygems ownership. This is said issue.

**Comment by jaredcwhite** [comment]
Hey RubyGems! I can vouch for Andrew taking over this Ruby gem. He's legit. 👍 (FYI I'm one of the core Bridgetown maintainers.)

**Comment by andrewmcodes** [comment]
Thanks @jaredcwhite, we will see what they say.

**Comment by andrewmcodes** [comment]
I am now the owner 👍
